language: android
jdk: oraclejdk8
env:
  matrix:
  - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a
android:
  components:
  - platform-tools
  - tools
  - android-22
  - build-tools-21.1.1
  - extra-android-m2repository
before_script:
- cp keystore.properties.example keystore.properties
- cp local.properties.example local.properties
script: "./gradlew clean assembleDebug"
deploy:
  provider: releases
  api_key:
    secure: IzDuRCD8EEZ6LFe8xzBnp1roZ6tx5gC8pLtJZQ6FpdRF1L6gOEB/4o1ruPwVJBb3iz3TlYhMvrEmZo2oAkFOE6o1fzKpjMCl+olHxA1CGVBWQKBEm9CLpH73+/GVeFjg+jUyCsvumFJ/8OG12cxiIq3KPglm71nbWKavqxUGO78=
  file: ${TRAVIS_BUILD_DIR}/app/build/outputs/apk/app-debug.apk
  on:
    repo: dinosaurwithakatana/holo_hacker_news
    branch: master
    tags: true
    all_branches: true
